post_install()
{
    echo "run winetricks glsl=disable ; winetricks vcrun2010 usp10"

    echo "also set ~/Documents/My Games/Path of Exile/production_Config.ini to:"
    echo "[GENERAL]"
    echo "engine_multithreading_mode=disabled"
    echo "[DISPLAY]"
    echo "shadow_type=no_shadows"
    echo "post_processing=false"
    echo "texture_filtering=1"
    echo "antialias_mode=0"
    echo "screen_shake=false"
    echo "texture_quality=1"
}

post_upgrade()
{
    post_install
}
